source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’

use_frameworks!

target ‘Photage’ do
    pod 'AFNetworking', '2.6.1'
    pod 'SDWebImage', '3.7.0'
    pod 'InstagramKit', '~> 3.8'
end
